### ISSUE TITLE
Georgetown hangs waiting for waterloo

### ISSUE THREAD

**Issue by gvcormac** [trec-dd/trec-dd-assessing#11]
Gateway Time-out

The gateway did not receive a timely response from the upstream server or application.

**Comment by isoboroff** [comment]
Is this an issue for Adam or for Shiqi?  I can't tell from the report.

**Comment by gvcormac** [comment]
I don't know whose issue it is.   Probably a protocol mismatch.

**Comment by shawn67** [comment]
On which page and what operation did this happen, I need to reproduce this to check

**Comment by aroegies** [comment]
Looking at my logs, it looks like several requests were made for /ranked/10/20 in a short time span. 

However, we only ever serve the first request for a document pull when there are multiple on-going requests for the same topic. The remainder are rejected with 404s since there is a pending request for the same topic. 

I would hypothesize the hang results from GTown's side seeing a 404 and not getting into a stuck state when the first request is filled.

This issue never cropped up during our internal testing.

**Comment by gvcormac** [comment]
User (me) behavior that likely caused this was repeated clicking of "discard" (or whatever the button is called) to try to see some new documents.

**Comment by aroegies** [comment]
There does appear to be a 60 or so second delay from when the GTown request was made until was fulfilled. 

Which may have resulted from the topic being created immediately before that. It is unclear.

**Comment by gvcormac** [comment]
At the moment, due to a temporary patch I put in when loading the new data, topic creation takes a long time.  I will fix this later today.   You should not send any requests for a topic until the topic creation finishes.

**Comment by aroegies** [comment]
How does one know when it finishes?

**Comment by shawn67** [comment]
Intend to add a button to show many documents completed and discarded for this topic, when reach a certain number then the assessor decides to finish.

**Comment by gvcormac** [comment]
Good question.  The next command will wait until the previous one finishes.  So long as you don't queue up unfinished commands, things should be fine.  So I'll rephrase what I said:  you can in fact issue a query before topic creation finishes, but at most one.  You have to wait for it to finish.

**Comment by gvcormac** [comment]
It appears the issue here is that when you sent judgments to Waterloo for documents that were found with Lemur, Waterloo has to look them up.  Given the size of the Ebola dataset, and the fact that we are doing a disk-crunching build on the server machine, this takes a long time and the UI gives up.

After the UI gives up, it is locked.  But you can switch domains, and switch back again, and continue.
I will look into this performance issue, but not until after I have loaded the Blackhat documents.

**Comment by gvcormac** [comment]
I believe I have solved the long delay problem.  Response time should be sub-second.

**Comment by shawn67** [comment]
time out error catching added at our side. refer to #23
