### ISSUE TITLE
Can't login as any assr

### ISSUE THREAD

**Issue by gvcormac** [trec-dd/trec-dd-assessing#14]
They all flash a subliminal image of the UI, then revert to login screen.  Just like assr10 did for me last night, but this time without provocation.

**Comment by shawn67** [comment]
Which account are you using? not happening at my side.

**Comment by isoboroff** [comment]
I'm also seeing this, as assr1.

**Comment by gvcormac** [comment]
assr10, assr9, assr8, assr4

**Comment by gvcormac** [comment]
Tried assr6 in fresh Safari session (previously using Firefox).  Got in, but then when I logged out could not get in to assr10, or back in to assr6.  Tried Firefox private browsing, still no go.

**Comment by shawn67** [comment]
Ian and Gordon,

can you confirm on this again? because at my side i tried different browsers, not encountering this. And for assr10,  I reset it's page log, should be able to log in right now.

**Comment by isoboroff** [comment]
Now I can log in, as assr1 or assr10.

**Comment by gvcormac** [comment]
It works now.
