### ISSUE TITLE
Removing [annoying] delete confirmation popup broke delete

### ISSUE THREAD

**Issue by gvcormac** [trec-dd/trec-dd-assessing#21]
I clicked the [very welcome] "don't ask me again for this page" button on discard.  But now discard doesn't seem to work at all, after clicking "don't ask".

**Comment by shawn67** [comment]
You mean discard?

**Comment by gvcormac** [comment]
Yes.  Discard.

**Comment by shawn67** [comment]
I think keep all the doclist updating/discard/complete problem in the same thread. They are all related interaction. It would be easier for the discussion.
