### ISSUE TITLE
Click 'completed' from search, can't return to search

### ISSUE THREAD

**Issue by isoboroff** [trec-dd/trec-dd-assessing#27]
From a search results list, click on a document, highlight a passage and drag it to a subtopic.  Then clck 'completed'.  This takes me to a new screen with a link that says "<-- search", but this doesn't take me back to my search page, instead I go back to the query box.  I should be able to go back to the search.

Alternatively, perhaps 'completed' and 'discard' should only be used during browse?  Have to think about that one.

**Comment by shawn67** [comment]
I would propose :
support search mode with a viewed doc button;
support browse mode with a completed and discarded doc button;

this would be easier to accomplish in my implementation level, and if that make sense to the user experience too, i hope we can settle this down.

**Comment by isoboroff** [comment]
I just realized... the buttons on the bottom in the search window are navigational, not for selecting the status of a document being reviewed.

This is a workflow issue:  During search, they can select document passages to feed to the learning process.  During browse, they should mark docuemnts as complete or discard.  I'm going to close this issue.
