### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by isoboroff** [trec-dd/trec-dd-assessing#8]
Clicked on a link in browse, and got an ISE.

Side issue: ISE and other errors tell me to report to root@localhost.

![list](https://cloud.githubusercontent.com/assets/248436/7059348/8cf09ea0-de3d-11e4-93db-327487027c3f.png)
![ise](https://cloud.githubusercontent.com/assets/248436/7059349/8ffbe500-de3d-11e4-9094-169d48a7d5d7.png)

**Comment by isoboroff** [comment]
(clicked on the 5.91388 document in the list.  Also with later documents.  Earlier docs in the list still come up.)

**Comment by shawn67** [comment]
Appears to be some doc the they recommended not found on our side. Should be fixed after we check the doc key lists.

**Comment by shawn67** [comment]
duplicate with #17
