### ISSUE TITLE
Incorrect "judgments" csv file submitted to waterloo

### ISSUE THREAD

**Issue by gvcormac** [trec-dd/trec-dd-assessing#9]
Georgetown seems to send use correct csv files sometimes, and incorrect other times.  I show
below a correct example, and an incorrect example, both from this evening.  Note that commas
and newlines must be replaced by spaces in the passage field --- but I don't think this problem 
fully explains the issue. 

[earlier I said commas and newlines must be escaped, but I was mistaken. they must be eliminated]

=== correct example ===

/judgements/1
2,Ebola,1,assr1,1,west african hospital,0,null,0,null,ebola-e33d07b986dab12f7f41944643798d21729eea8e1cbc3a6939a9e01247f0b8e8,0,0,-1
2,Ebola,1,assr1,1,west african hospital,0,null,0,null,ebola-75442646cad8aae4b18efc78e22a7f3ad2335d358b61452932edca296a62113f,0,0,-1
2,Ebola,1,assr1,1,west african hospital,0,null,0,null,ebola-c8e29d0ae0a52eb3dc82af7600faec7aa99ea81778bb4b3443cd4703ef0a885b,0,0,-1
2,Ebola,1,assr1,1,west african hospital,0,null,0,null,ebola-823e65f47141b6c14dcb7624a6a721ee865cbc5e99e6bb23a4b2ed2b955787cb,0,0,-1
2,Ebola,1,assr1,1,west african hospital,0,null,0,null,ebola-e4aa3db58425c863df117b7e784f62477a9346feb3c5f59294646aef448bc130,0,0,-1

=== incorrect example

/judgements/4
1,Illicit_Goods,1,assr1,4,email addresses,4,lists for sale,7,I have a list with 10 million email addresses from people of the US~ any
interest?,com_blackhatworld_www_e52ec221ea50ae047d1c49cdc6f5001c9fc28db4_1426359795456,0,0,3,
1,Illicit_Goods,1,assr1,4,email addresses,4,lists for sale,8,I'm selling
.edu email addresses for $2 each.,net_hackforums_www_eafcce0e18bdb5aeeba8dfe531e8863d606ba9e5_1424905228608,0,0,3,
1,Illicit_Goods,1,assr1,4,email addresses,5,requests for lists,6,I hope I put this on the correct thread.

I need a list of email addresses (2000 at least). Our target are people in the
Panama or Central USA areas. Email marketing will be for buying and selling
cars,com_blackhatworld_www_e52ec221ea50ae047d1c49cdc6f5001c9fc28db4_1426359795456,0,0,4,
1,Illicit_Goods,1,assr1,4,email addresses,5,requests for lists,11,i need HR Contacts of all companies
in gulf location IT ~ Non IT ~ Construction companies ~ interior companies,net_hackforums_www_3a97123c9af640c79e703af4504d41d6c0c8c2cc_1424957039222,0,0,2,

**Comment by shawn67** [comment]
fixed(newline replace missing)
